### ISSUE TITLE
PATCH Request to have a MAX_QUEUE_CAPACITY

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#111]
To support https://github.com/SimplQ/simplQ-frontend/issues/425 we need to add an extra property to the queue: MAX_QUEUE_CAPACITY.

1. When a queue is created, it will be set to -1, and -1 indicates infinite/no limit.
2. We will need to at a PATCH request to the queue resource to update the capacity limit
3. When we add a new token, we need add to the queue only if the limit has not reached.
4. `/queue/status` should return the remaining slot count if the field is not set to -1

**Comment by chalx** [comment]
@daltonfury42 this one can be closed.

**Comment by daltonfury42** [comment]
Thanks, @chalx

**Comment by daltonfury42** [comment]
@chalx's PR #114 has done (2) in the issue description, 1, 2 and 4 are left. Reopening.
