### ISSUE TITLE
Regression: Server responds with 500 error to every request

### ISSUE THREAD

**Issue by mradenovic** [SimplQ/simplQ-backend#118]
Login from `http://localhost:3000/` works.
When login is attempted from `https;//simplq.me` it fails with message:

<strong>
Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
Please go to the <a href="https://manage.auth0.com/#/applications/9BAywifjAy6n0sx8WbuQubMGGjofpwd6/settings" >Application Settings page</a> and make sure you are sending a valid callback url from your application.
</strong>

**Comment by daltonfury42** [comment]
This is fixed. Thanks for reporting.

I had put testing into back burner. We need to start thinking of testing soon!
