### ISSUE TITLE
Token Number Generation

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#12]
A strong point which brought back token number to the table was the scenario where two people with the same name are present in the queue. So, we decided that it would be required to also generate a running (1, 2, 3, 4..) tokenNumber for each user.

This will not replace anything in the current system. This is different from `tokenId` which is the UUID/PRIMARY_KEY generated for the user joining the queue. 

Task: Add an extra `tokenNumber`  field to the DB, and return it with tokens (`GET /queue/{queueId}` and `GET /token/{tokenId}`)

**Comment by pavan541cs** [comment]
#65 Should close this
