### ISSUE TITLE
Backend Support for queue history

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#126]
Currently backend returns only the active tokens on calling `GET /queue/<queue-id>`.

To support queue history, we would need to do two things:

1. Record the deletion timestamp for each token
2. Add a list of `removedTokens` to  the [QueueDetailsResponse](https://github.com/SimplQ/simplQ-backend/blob/master/simplq/src/main/java/me/simplq/controller/model/queue/QueueDetailsResponse.java#L28) which will have the deletion time.

**Comment by daltonfury42** [comment]
Relates to https://github.com/SimplQ/simplQ-frontend/issues/601

**Comment by lanemets** [comment]
@daltonfury42 Would you mind if I start working on it?

**Comment by Soumit915** [comment]
@daltonfury42 , I am working on the frontend for this issue, I have noticed that we can easily implement the history of the queue, if we can somehow store a list of objects that consists of : 
{
   token_id: ..,           //token of the person who performed an action
   name: ...,               //name or id of the person who performed an action
   action: ...,              //type of action performed, if he was added(0), removed(1), joined(2), notified(3). We can use integer values to store the type of action
   timestamp: ...        //timestamp of the action being performed
}

**Comment by Soumit915** [comment]
> @daltonfury42 , I am working on the frontend for this issue, I have noticed that we can easily implement the history of the queue, if we can somehow store a list of objects that consists of :
> {
> token_id: .., //token of the person who performed an action
> name: ..., //name or id of the person who performed an action
> action: ..., //type of action performed, if he was added(0), removed(1), joined(2), notified(3). We can use integer values to store the type of action
> timestamp: ... //timestamp of the action being performed
> }

Pls, guide

**Comment by daltonfury42** [comment]
@Soumit915 that's a great idea, we should do this. Let's have a new `GET /queue/<queue-id>/events` endpoint that returns a list of events that happened to the queue. We can return tokenNumber, tokenName, action (added and removed would do for now), and timestamp.

Thanks a lot.

**Comment by Soumit915** [comment]
```
[
        {
            "action": "ADDED",
            "name": "Soumit Saha",
            "tokenNumber": 1,
            "actionTimestamp": "2021-08-24T11:41:13.833+0000",
        },
        {
            "action": "NOTIFIED",
            "name": "Soumit Saha",
            "tokenNumber": 1,
            "actionTimestamp": "2021-08-24T11:41:13.833+0000",
        },
        {
            "action": "REMOVED",
            "name": "Soumit Saha",
            "tokenNumber": 1,
            "actionTimestamp": "2021-08-24T11:41:13.833+0000",
        },
	 {
            "action": "PAUSED",
            "actionTimestamp": "2021-08-24T11:41:13.833+0000",
        },
	 {
            "action": "RESUMED",
            "actionTimestamp": "2021-08-24T11:41:13.833+0000",
        }
    ]

```

I have shared the example JSON, above. Can you please create the `GET /queue/<queue-id>/events` , so that the history can be easily implemented. 

The JSON has, two variablity, when the action will be `ADDED`, `REMOVED`, `NOTIFIED`,

**Comment by Soumit915** [comment]
Hey, I have mentioned in the thread on github. Please, create the
api-route  /queue/<queue-id>/events , so that I can implement it in the
front-end. Please do reply and help

**Comment by daltonfury42** [comment]
Hi Soumit. Hoping that this is not an urgent customer requirement. I will be able to add the API only the next weekend.

We should merge [Anjali's PR](https://github.com/SimplQ/simplQ-frontend/pull/646), merge it to your work and make the changes for the proposed backend API. Please leave any comments on her PR which would help you later when you merge her work. Thanks.
