### ISSUE TITLE
[Code Quality] Lombok

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#14]
Can we use [Lombok](https://projectlombok.org/) to reduce some boiler plate code?

**Comment by avinashkris9** [comment]
Hello, I am a first time contributor. I would like to pick this activity. Could you help me for environment setup.  Do I have to create my own AWS credentials ? 

Get below error if I compile and run as mentioned in Readme.

`nable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables`

**Comment by daltonfury42** [comment]
Hi @avinashkris9, sure, let me help you with that. 

This exception would come for anyone trying to run code manually. It might be a good idea to not check for credentials unless the AWS_PROFILE environment variable is set. That way, people setting up backend locally would not need to go through the extra step of setting credentials. It would be a quick change, give me a moment.

**Comment by daltonfury42** [comment]
This has been taken care of. @avinashkris9 can you take the latest master?

**Comment by avinashkris9** [comment]
Thanks. Yes. Now I am able to run locally.

**Comment by avinashkris9** [comment]
Please assign the issue to my id. I have raised [https://github.com/SimplQ/simplQ-backend/pull/26 ] . Please review.

**Comment by daltonfury42** [comment]
Resolved by #26
