### ISSUE TITLE
Hardcoded URL in Token.java

### ISSUE THREAD

**Issue by farisshajahan** [SimplQ/simplQ-backend#147]
URL_PREFIX is hardcoded inside [Token.java](https://github.com/SimplQ/simplQ-backend/blob/master/simplq/src/main/java/me/simplq/dao/Token.java) and should ideally be changed to an environment file from which the value should be obtained. Hardcoding causes problems to users who might host their own instance of SimplQ on their servers.

**Comment by daltonfury42** [comment]
That's a good catch. We should read from a environment variable, and then default to the current value in the properties file [here](https://github.com/SimplQ/simplQ-backend/blob/master/simplq/src/main/resources/application.properties#L6).

**Comment by lanemets** [comment]
@farisshajahan @daltonfury42 Hi! I can take this issue if you don't mind. 
I'm going to move URL_PREFIX to applicaton.properties and maybe move payload creation functionality to a separate component.

**Comment by daltonfury42** [comment]
Sure, go ahead.

**Comment by daltonfury42** [comment]
Thanks @lanemets
