### ISSUE TITLE
getOwnerOrElseCreate() in OwnerService uses orElse instead of orElseGet

### ISSUE THREAD

**Issue by farisshajahan** [SimplQ/simplQ-backend#148]
```@Transactional
  public Owner getOwnerOrElseCreate() {
    var ownerId = loggedInUserInfo.getUserId();
    return ownerRepository.findById(ownerId).orElse(ownerRepository.save(new Owner(ownerId)));
  }
```

According to the docs for `Optional.orElse()`, the statement inside orElse() (i.e `ownerRepository.save(new Owner(ownerID))`)  is evaluated even when `findById(ownerId)` finds the Owner object and returns it. The reason it doesn't create problems right now is because `CRUDRepository.save()` merges an Object with another in the DB if the `id` passed is already present in the DB. This behaviour should be changed and we should resort to using `orElseGet()` instead as follows:

```
@Transactional
  public Owner getOwnerOrElseCreate() {
    var ownerId = loggedInUserInfo.getUserId();
    return ownerRepository.findById(ownerId).orElseGet(() -> ownerRepository.save(new Owner(ownerId)));
  }
```
This will ensure `ownerRepository.save(new Owner(ownerID))` is executed only when `findById` finds no matching object.

**Comment by daltonfury42** [comment]
Nice catch. I didn't know this!

**Comment by sijinpavithran** [comment]
Hi. I would like to work on this.

**Comment by daltonfury42** [comment]
Sure, go ahead.

**Comment by sijinpavithran** [comment]
Thanks. I have been trying to setup the project on my pc. Facing some difficulty. Could you please share gitter chat details so I can connect & solve my doubts?

Regards.

**Comment by daltonfury42** [comment]
You can send the problem here, it might be better

**Comment by daltonfury42** [comment]
Thanks all, closing the issue.
