### ISSUE TITLE
[Infra] CI/CD, Dev and Prod Environments for Backend

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#15]
Current backend deployment is fully manual. We need to automate.

Also there is only one instance now. Dev server like we have for UI is needed.

**Comment by thehamzarocks** [comment]
CI/CD pipeline has been set up using AWS CodePipeline.
A new deployment will be created every time code is checked in to master.

As discussed with @daltonfury42, we can have both dev and prod versions running in the same instance on different ports.

**Comment by thehamzarocks** [comment]
To save on buildminutes, we'll be using Travis CI for dev builds and CodePipeline for PROD.

**Comment by daltonfury42** [comment]
@thehamzarocks Can we configure travis to be triggered just on all commits to master?

**Comment by daltonfury42** [comment]
Getting this done right, and having a dev and prod environment is very critical, if you think of it, if we are to have a product that doesn't break every now and then.

This task is a bit more wider in scope, we should have separate databases for dev and prod, and the two could be having different schemas whenever we change the schema. (Prod would still be having the old schema, and dev the updated schema).

Having two database servers will cost us, so we will have to have multiple databases inside the same schema. Then the next question would be, how we switch between the h2 inmemory db on local, dev db on dev instance and prod db on prod. Can we use spring profiles for this? @thehamzarocks or you have other solutions in mind?

**Comment by thehamzarocks** [comment]
Here's a draft plan. What do you think? @daltonfury42 

1. We already have a Travis-CI deployment for master and AWS Codepipeline for prod. We can move the prod build to Travis-CI in the future.

2. We should have two services in systemd. Each will point to the corresponding jar (dev/prod) and execute the jar with different jvm parameters (-Dspring.profiles.active=dev)

3. We have two Deployment Groups already - one for dev and one for prod. We can use the env variable provided by CodeDeploy: DEPLOYMENT_GROUP_NAME in the runJar.sh to choose the appropriate service to run. We should rename our deployment groups to be clearer.

**Comment by thehamzarocks** [comment]
We have all the conf handled by service files (hacky), but still need to point the codedeploy env for prod to a different location than the current dev one: /deployed/complete

**Comment by daltonfury42** [comment]
Right. This will all be solved with your conf changes!!

**Comment by daltonfury42** [comment]
@thehamzarocks Can we close this?
