### ISSUE TITLE
Proper REST API design

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#16]
A draft proposal:

Endpoint | Description
-- | --
GET /v1/queue/`<queue-id>` | Get All Users Inside the Queue if the requestor is admin, else just return queue metadata, mainly queue name and status
POST /v1/queue | Create a new 
POST v1/queue/`<queueId>`/ | Add a entry to the queueparams: name, mobilereturn: token-id
GET v1/queue/`<queueId>`/`<tokenId>` | Returns the status of token
DELETE v1/queue/`<queueId>`/`<tokenId>` | Removes from queue?
POST v1/queue/`<queueId>`/`<tokenId>` | Notify user?

**Comment by thehamzarocks** [comment]
1.  Are some of the above endpoints currently unimplemented?
2. Get All Users Inside the Queue if the requestor is admin, else just return queue metadata, mainly queue name, and status - these should be two distinct endpoints.

**Comment by thehamzarocks** [comment]
REST API:
https://docs.google.com/spreadsheets/d/11e9VmPXeru_E4bmMOjjULOa9Giz99gTPNI2NUy6s7r4/edit?usp=sharing

**Comment by daltonfury42** [comment]
donee
