### ISSUE TITLE
PublicQueueTask1: Queue Name Should be Unique

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#17]
In a step closer to moving towards public/discoverable queues and also to make the shared URL more human readable, we would need to put a uniqueness constraint on the queue name.

Handling of whitespaces, capitalization and stripping of non url special characters might be required, so names "Joy Mart" and "Joy    Mart" and "Joy mart" would all be duplicates.

**Comment by thehamzarocks** [comment]
Instead of separate handling, it would be better to just put constraints on queue names so they don't contain these special characters.

**Comment by daltonfury42** [comment]
Hmm, have to think about it. Can we allow the special characters in the name, but keep a separate field in the DB for the queue-url where we clean the user input to create the url?

Queue Name from user: "  Holla & Hemi   Market.   "
Queue Name stored in the DB: "Holla & Hemi Market."   
(white space stripped on beginning and end, and multiple spaces combined to single)
Queue Url Stored in DB: holla-hemi-market
(Should be unique, else return error)

The rationale behind this is that putting constraints like no special characters would result in bad UX. Someone would try creating "Ron's Pub" and then we return a error message, he would have to then try again removing the semi colon, which he won't like to remove from his store's name.

**Comment by daltonfury42** [comment]
We can keep it unique for now, and as a next step, we should append a small random string to it in case of collision

**Comment by thehamzarocks** [comment]
For better user experience, we should be able to validate the queue name for uniqueness even before the user hits create queue.
