### ISSUE TITLE
PublicQueueTask4: Pause and Delete Queue Functionality 

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#20]

**Comment by pavan541cs** [comment]
@daltonfury42 Can I pick this one ?

**Comment by daltonfury42** [comment]
Yes, that would be a good task to pick up. We would need to introduce a new `QueueStatus` field in the queue entity. It can be an enum with three states, ACTIVE, PAUSED, and DELETED. Other endpoints would have to return the statues at appropriately, and join queue should fail with the right reason if it's paused or deleted.

I am thinking we can expose this functionality to the UI like this:

```
POST /v1/queue/status
{
  "queueId": "<the-id>"
  "newStatus": "DELETED"
}
```

(We already have a `GET /v1/queue/status`). What do you think?

A more challenging and fun task would be https://github.com/SimplQ/simplQ-backend/issues/69 The approach/design should be fixed first. Can you take a look and comment there about what you think?

**Comment by pavan541cs** [comment]
Lets introduce `QueueStatus` into Queue entity and return that in the `status` endpoint and introduce `/v1/queue/pause/{queueId}` to pause the queue and `DELETE /V1/queue/{queueId}` to delete the Queue. Delete implies setting the status of the queue as `DELETED`

**Comment by daltonfury42** [comment]
Honestly I am not an expert at REST endpoint design. These endpoints look good to me. Let's ask @thehamzarocks what he thinks.

What verb will `/v1/queue/pause/{queueId}` use? Also, how would you resume a queue? `/v1/queue/resume/{queueId}`?

**Comment by thehamzarocks** [comment]
If you want to pause/resume a queue, a PUT on the queue would suffice?

PUT /v1/queue/{queueId}
with the corresponding status entry in the payload?

Since we are modifying the queue object after all.
This makes our API simpler.

**Comment by daltonfury42** [comment]
Yeah, this makes sense.. Otherwise I see a explosion in the endpoints... It should be a POST and not a PUT, right?

**Comment by pavan541cs** [comment]
I think it should be a PUT

**Comment by thehamzarocks** [comment]
We're not creating a new queue, right? So PUT with the queueId would suffice.
We could use POST if we haven't supported PUT, we'll just have to add the queueId to the request payload instead.

POST /v1/queue

**Comment by daltonfury42** [comment]
Ok got it!
