### ISSUE TITLE
Constraints on Queue Name

### ISSUE THREAD

**Issue by thehamzarocks** [SimplQ/simplQ-backend#23]
As the queue name should be directly inputable on the URL, it should not contain any spaces or special characters, and there should be UI and backend validations for the same.

**Comment by daltonfury42** [comment]
We can use spring bean validation for this: https://reflectoring.io/bean-validation-with-spring-boot/

**Comment by nirmalkv** [comment]
Adding a regex which allows alphanumerics and -._~. Do we have any naming conventions? Also leaving the validations to its default behavior which is to send 400 bad request. Will that be enough to catch the error at UI?

**Comment by daltonfury42** [comment]
Let's allow only numbers, alphabets and hyphens. Yes, let's do the default behaviour.

I didn't get what you are asking about naming conventions.

**Comment by nirmalkv** [comment]
It's what you said only, whether there there are any more constraints on allowed queue names.

**Comment by daltonfury42** [comment]
This is good for now. I can't think of any.
