### ISSUE TITLE
Use Spring Profiles

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#66]
We should have three profiles, `dev`, `prod` and `default/local`.

1) We should load a `MockSmsService` bean unless it's `prod` profile. https://github.com/SimplQ/simplQ-backend/blob/master/complete/src/main/java/com/example/restservice/service/smsService/TexLocalSmsService.java

Then we can avoid commenting out line 31 in the above file.

2) Similarly, a SecretsManager should not be loaded on `default/local` profile.

https://github.com/SimplQ/simplQ-backend/blob/master/complete/src/main/java/com/example/restservice/service/SecretsManager.java

These were temporary solutions that then we can then remove:
https://github.com/SimplQ/simplQ-backend/blob/master/complete/src/main/java/com/example/restservice/service/SecretsManager.java#L27
https://github.com/SimplQ/simplQ-backend/blob/master/complete/src/main/java/com/example/restservice/service/SecretsManager.java#L61

**Comment by pavan541cs** [comment]
I will work on this today @daltonfury42
