### ISSUE TITLE
Configuration to disable SMS in Prod

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#70]
Currently SMS is enabled in prod after #68. We would need to control it via `application.properties`

**Comment by nikita-tyagi** [comment]
@daltonfury42 I would like to contribute. How to get started?

**Comment by daltonfury42** [comment]
Sure. Welcome. This is an easy task that can get you started, and then you can go on and take bigger ones. Can you fork the repository and get it running on your local?

You can then use the postman collection in the readme to test your setup.

For this task, you'll have to put a new property inside `application.properties`, `sms.enabled=false`. 

Then in the below file, SMS should be send only if the property was set to false. https://github.com/SimplQ/simplQ-backend/blob/master/complete/src/main/java/com/example/restservice/service/smsService/TexLocalSmsService.java#L31

**Comment by nikita-tyagi** [comment]
Okay. I will start looking into this thank you!

**Comment by dhirenmathur** [comment]
Is this up for grabs?

**Comment by daltonfury42** [comment]
@nikita-tyagi has raised an open PR for this. It was pending my review, I missed it. I'll let her complete this if she wants to.
