### ISSUE TITLE
GET on /queues and /tokens should return sorted by creation time

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#76]

**Comment by nikita-tyagi** [comment]
Can I start working on this issue?

**Comment by daltonfury42** [comment]
Sure. This can be a good task for you after you complete https://github.com/SimplQ/simplQ-backend/pull/78

**Comment by dhirenmathur** [comment]
Hi @daltonfury42, looks like this is still up for grabs, I'm looking to get started with #hacktoberfest in a couple of days, mind if I pick this up then if this is still an issue?

**Comment by daltonfury42** [comment]
Sure, go ahead.

**Comment by dhirenmathur** [comment]
Hi @daltonfury42 , just getting set up here - for some reason code traversal isn't working in intellij for me, do you have any tips? 
Also, what how should the responses be sorted, oldest first or newest first?

**Comment by daltonfury42** [comment]
Not sure why. It's working at my end. 🤔 

You should open `simplQ-backend/complete`, it should open as a maven project. Try `mvn clean package` from within intellij... but this shouldn't have to do with code traversal

Oldest first.

**Comment by dhirenmathur** [comment]
Hm ok, i'll see why else traversal could not work. 
I tried to simulate the scenario to check the current behaviour and it looks like it already returns oldest first? 
![image](https://user-images.githubusercontent.com/19893222/94798319-193e7700-03ff-11eb-94e7-7a85c7c3466e.png)

Do you have an irc/discord/telegram to discuss further?

**Comment by daltonfury42** [comment]
Let's discuss over the PR itself. It happens to come sorted, but we need to guarantee it.

Your would ensure this happens. For example something in the DB layer might change, and it would be a good to have to ensure this at service layer, or so I thought.

**Comment by dhirenmathur** [comment]
Makes sense, I have incorporated your feedback.
