### ISSUE TITLE
Queue post fails on certain inputs

### ISSUE THREAD

**Issue by PavanDongare** [SimplQ/simplQ-backend#81]
Inputs
ssss
qqqq

response:-
error: "Internal Server Error"
message: "could not execute statement; SQL [n/a]; constraint [uk_4emkh34msxtqa7blxlcimoqy9]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"
path: "/v1/queue"
status: 500
timestamp: "2020-09-04T22:29:35.600+0000"

**Comment by daltonfury42** [comment]
This is because a queue by the same name already exists. We need to fix
this, to give the property readable error from backend

**Comment by daltonfury42** [comment]
This is resolved in #84
