### ISSUE TITLE
Adding an end to end integration test

### ISSUE THREAD

**Issue by dhirenmathur** [SimplQ/simplQ-backend#86]
>We should write one such testcase, which creates a queue, and then create a token in the queue. The in-memeory DB should work. Even asserting 200 OK is enough for now.

**Comment by dhirenmathur** [comment]
@daltonfury42 I'm still not able to get the intellisense thing working in the IDE, it's very difficult to work without automatic imports, code suggestions, code traversal etc 
I tried with both openjdk11 and oracle-jdk 11, on two different machines with no luck. If you get some timcle can you check on a different machine and help me out? 

Just wanted to get some help on the aforementioned issue because it makes it really frustrating having to copy over import statements from other files or projects, compilation errors due to a small typo due to lack of autocomplete etc (very first world problems I realise lol) 

On the integration test front, dealing with some application context issues to get the test running, it's still a WIP. Currently working on tests for the queue controller.

**Comment by daltonfury42** [comment]
mahn... that' a real pain, manual importing. I don't have a spare machine to try on, but let me reimport and see what happens... if not we can come together on google meet and try to figure this out.

**Comment by daltonfury42** [comment]
I'm not able to reproduce the issue at my end. I've send you a connection request on LinkedIn. Let's look at it together?

https://meet.google.com/xja-hcyn-skj

**Comment by dhirenmathur** [comment]
Sounds good, ping me there when you're ready.

**Comment by dhirenmathur** [comment]
Thanks for helping fix this, it's way better now 👍🏻

**Comment by daltonfury42** [comment]
Check this out: https://martinfowler.com/articles/practical-test-pyramid.html

They [claim](https://github.com/rest-assured/rest-assured/wiki/GettingStarted#spring-mock-mvc) to go well with MockMvc too.

**Comment by dhirenmathur** [comment]
Will do. Sorry about the delay, I didn't get much time, and what I tried didn't work.

**Comment by daltonfury42** [comment]
We are now mocking out the auth filter. https://github.com/SimplQ/simplQ-backend/pull/104/commits/7a4bc7e16591e5395f7f5c8e449c694868659836
