### ISSUE TITLE
travis.yaml file contains hardcoded token 

### ISSUE THREAD

**Issue by dhirenmathur** [SimplQ/simplQ-backend#88]
While `travis.yml` file is hidden from the github UI it isn't good practise to have a hardcoded token, we should store the token in Github secrets for the repository and use an environment variable to access it in the script. 

This should have no impact on local dev environment setup as travis isn't used anywhere locally.

**Comment by daltonfury42** [comment]
I believe this token is safe to keep publicly. This is our repo's access token, excepted using TravisCI's private key. So only TravisCI servers can read it, it's ok to keep it public.

https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml
