### ISSUE TITLE
Let Users Sign Up using Google

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-backend#91]
We currently have some authentication, but that is not perfect. We are using AWS Cognito, but [integrating Google Sign](https://developers.google.com/identity/sign-in/web/sign-in) would be easier and better for us.

**Current System**:Currently, a temporary userId and tempKey is generated and stored in the the local storage when someone visits simplq.me for the first time. It's used to authenticate with Cognito across sessions. This serves as an anonymous sign in. (This implementation currently has a bug: we are currently sending the identity token instead of access token, see discussion here #13)

**Requirement**: Users should be able to use SimplQ without needing to sign in. But at any given point, they can voluntarily sign up with us. Signing up will make sure that they can manage the queue using multiple devices, that the queue is not lost when the user switches to a new browser or clear local storage etc.

**Proposal**: We should use Cognito for maintaining anonymous users and then directly use Google Auth once they decide to sign up. Implementing Google sign in looks very easy: https://developers.google.com/identity/sign-in/web/sign-in

What will need to make sure that when the user signs up, all his current queues are carried over to the new identity. One possible way is to create an owner table where we store ownership information of each queue. (A one to many mapping from the unique id of the user to queueIds for which the user is an owner of). Currently we store ownership information along with the queue object. 

Before the user chooses to sign in via google, this mapping will have the temp user id which we created. Once the user signs up, we will have to update this table with whatever unique identifier that google provides us. 

**For future**: This design will allow us to have multiple owners for the same queue.

**Comment by pavan541cs** [comment]
Is this implemented @daltonfury42 ?

**Comment by daltonfury42** [comment]
No, in the frontend side, I ended up removing cognito altogether, as it didn't make sense to maintain cognito for anonymous authentication.

So, we use google sign in alone, and for people who are not signed in, [ we mark them as "anonymous" ](https://github.com/SimplQ/simplQ-backend/pull/95/files#diff-fae7615cbc86b000f3f79590357f199e9abbc877a9dbd18bb487d01b01c03811R40) and move on. 

In all requests when the user has not logged in, he sends "anonymous" instead of the token, in which case he is authenticated with the user id "anonymous" without any checks. https://github.com/SimplQ/simplQ-backend/pull/95

What we could do is to move out ownership information into a separate table. Current:
```
Queue Table: (queueId, queueName, ..., ownerId)  
Token Table: (tokenId, name, contactNumber, ..., ownerId)
```

to:
```
Queue Table: (queueId, queueName, ...)  
Token Table: (tokenId, name, contactNumber, ...,)
ACL Table: (objectId, userId, Role)
```

This would, in future allow multiple people to manage the same queue, and we could give multiple roles to different users. (ADMIN, OWNER etc..)

But I had not made the changes as I don't think I will be taking up this feature very soon.
